### ISSUE TITLE
Check for updates without password prompt

### ISSUE THREAD

**Issue by HarlemSquirrel** [franglais125/apt-update-indicator#16] opened 2017-08-03 16:58 UTC
In Ubuntu 16.04 I can check for updates with `aptdcon --refresh` as a normal user. If I enter this as the "Custom command to check for updates" then Apt Update Indicator prompts for my password to run this command with pkexec. 

I can install `packagekit-tools` and then the default `aptdcon --refresh` works without a password prompt. 

It would be nice to have an option to run a custom update check command without `pkexec` with a checkbox option or simply requiring the user to include `pkexec` in their command if the command needs it.

**Comment by franglais125** [comment] 2017-08-03 18:18
Hi! Thanks for reporting this. I wasn't aware that some commands didn't require `pkexec`, hence why I included it by default.

Can you run the master branch to check if the issue is fixed? I included [5c29b2cea9bea3b38a6bd40cd50b60626c3eb10f] as a fix.

Cheers

**Comment by HarlemSquirrel** [comment] 2017-08-03 18:30
Sure, I'll check now!

**Comment by HarlemSquirrel** [comment] 2017-08-03 18:37
Yup, it's working beautifully!

**Comment by franglais125** [comment] 2017-08-03 18:43
Sounds good! Thank you.

I'll close the issue now and upload a new version to e.g.o soon.

**Closed as completed by franglais125** 2017-08-03 18:43 UTC
